name: Build & tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2
    - name: apt
      run: |
        sudo apt-get update &&
        sudo apt-get install -y curl autoconf libtool-bin make &&
        curl -s https://packagecloud.io/install/repositories/varnishcache/varnish72/script.deb.sh | sudo bash &&
        sudo apt-get install -y docutils-common varnish-dev
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
